#pragma config(Sensor, in2,    speedcontrol,   sensorPotentiometer)
#pragma config(Sensor, in3,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl2,  onoff,          sensorTouch)
#pragma config(Motor,  port2,           fwheelmotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           gatemotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	if (onoff==1)/*when bump switch is pressed program starts*/{
		setMotorSpeed(fwheelmotor, 11); //normal ferris wheel speed
		setMotorSpeed(gatemotor, 127); //closes gate as the ferris wheel starts

		if (speedcontrol == 55){
			setMotorSpeed(fwheelmotor,13); //changes ferris wheel speed when the potentiometer hits 55
		}
    if (speedcontrol == 1000){
			setMotorSpeed(fwheelmotor,15); //changes ferris wheel speed when the potentiometer hits 1000
		}
    if (speedcontrol == 4095){
			setMotorSpeed(fwheelmotor,17); //changes ferris wheel maxes speed when the potentiometer hits 4095
		}
		while (lineFollower == 2064){
			wait(45); //delays the direction switch to allow for smooth transition after 3 complete rotations
			setMotorSpeed(fwheelmotor, -11); //changes ferris wheel direction

			if (speedcontrol == 55){
			setMotorSpeed(fwheelmotor,-17); //changes ferris wheel speed when the potentiometer hits 55
		}
    if (speedcontrol == 1000){
			setMotorSpeed(fwheelmotor,-15); //changes ferris wheel speed when the potentiometer hits 1000
		}
    if (speedcontrol == 4095){
			setMotorSpeed(fwheelmotor,-11); //changes ferris wheel maxes speed when the potentiometer hits 4095
			/*this set of if statements allows the speed to change using the potentiometer even when the ferris
			wheel changes direction */
	}
	setMotorSpeed(gatemotor, 0); //opens gate after the ferris wheel is done spinning

}
