#pragma config(Sensor, in2,    speedcontrol,   sensorPotentiometer)
#pragma config(Sensor, in3,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl2,  onoff,          sensorTouch)
#pragma config(Motor,  port2,           fwheelmotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           gatemotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
PsuedoCode:
-Click Bump switch to activate the ferris wheel and open the gate
-initial power of the ferris wheel at 15
-Turn potentiometer clockwise to increase the ferris wheel speed
-Once the white bottomed cart goes over the line follower 3 times, the ferris wheel changes direction
-Turn potentiometer clockwise to slow down the ferris wheel
-Once the white bottomed cart passes over the line follower 3 more times, the ferris wheel stops and the gate opens
*/

task main(){

	while (true) //This means the program while run once the first action is taken, which is the bump switch
	{
	if (SensorValue[onoff]==1)/*when bump switch is pressed program starts*/{
		setMotorSpeed(fwheelmotor, 11); //normal ferris wheel speed
		setMotorSpeed(gatemotor, 127); //closes gate as the ferris wheel starts

		if (SensorValue[speedcontrol] == 55){
			setMotorSpeed(fwheelmotor,13); //changes ferris wheel speed when the potentiometer hits 55
		}
    if (SensorValue[speedcontrol] == 1000){
			setMotorSpeed(fwheelmotor,15); //changes ferris wheel speed when the potentiometer hits 1000
		}
    if (SensorValue[speedcontrol] == 4095){
			setMotorSpeed(fwheelmotor,17); //changes ferris wheel maxes speed when the potentiometer hits 4095
		}
		while (SensorValue[lineFollower] == 2064){
			wait(45); //delays the direction switch to allow for smooth transition after 3 complete rotations
			setMotorSpeed(fwheelmotor, -11); //changes ferris wheel direction

			if (SensorValue[speedcontrol] == 55){
			setMotorSpeed(fwheelmotor,-17); //changes ferris wheel speed when the potentiometer hits 55
		}
    if (SensorValue[speedcontrol] == 1000){
			setMotorSpeed(fwheelmotor,-15); //changes ferris wheel speed when the potentiometer hits 1000
		}
    if (SensorValue[speedcontrol] == 4095){
			setMotorSpeed(fwheelmotor,-11); //changes ferris wheel maxes speed when the potentiometer hits 4095
			/*this set of if statements allows the speed to change using the potentiometer even when the ferris
			wheel changes direction */
	}
	setMotorSpeed(gatemotor, 0); //opens gate after the ferris wheel is done spinning
		}

}
